---
  swagger: "2.0"
  info:
    title: "play-swagger-iheart API"
    description: "Sample application experimenting with swagger"
    version: "1.0.0"
  consumes:
    - application/json
  produces:
    - application/json